#!/bin/bash

if [ -d code ]; then cd code; fi

../scanner ../../proto/wayland.xml
../scanner ../../proto/xdg-shell.xml

#../scanner ../../proto/xdg-decoration-unstable-v1.xml
#../scanner ../../proto/wayland-drm.xml
#../scanner ../../proto/linux-dmabuf-unstable-v1.xml

# --- last line ---
