#!/bin/bash
# -*- scheme -*-

NYACC=$HOME/repo/sv/nyacc/current
export GUILE_LOAD_PATH=$GUILE_LOAD_PATH:`pwd`/..:$NYACC

exec guile $0 "$@"
!#

(use-modules (kbd-parse))

(case 3
 ((1) (test-reader-lo "keymap.txt"))
 ((2) (test-reader-hi "keymap.txt"))
 ((3) (test-reader-kv "keymap.txt"))
 (else #f))


;; --- last line ---
